"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _post_card from './post-card.bones.json'
import _compat_score from './compat-score.bones.json'
import _kviz_question from './kviz-question.bones.json'
import _notification_list from './notification-list.bones.json'

configureBoneyard({"color":"#EFEAE1","darkColor":"#2A2622","animate":"shimmer","shimmerColor":"#F8F4EC","darkShimmerColor":"#3A332C","speed":"1.6s","shimmerAngle":110,"transition":200})

registerBones({
  "post-card": _post_card,
  "compat-score": _compat_score,
  "kviz-question": _kviz_question,
  "notification-list": _notification_list,
})
